### ISSUE TITLE
Error: connect ETIMEDOUT 46.229.161.160:80

### ISSUE THREAD

**Issue by iggyZiggy** [ithinkdancan/node-semrush#7]
my app keeps crashing because of errors like this, and crashes are few times a week or sometimes once a day. Other than timeoutes got these as well:

```
Error: getaddrinfo ENOTFOUND api.semrush.com api.semrush.com:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

last error is more often.
Is this official node module from semrush?

**Comment by ithinkdancan** [comment]
@iggyZiggy are you still having connection issues?

**Comment by iggyZiggy** [comment]
can't remember when was the last time i've got it, but i didn't update node module in a while, I guess this wasn't fixed in module but on backend?
